require("weihang.options")
require("weihang.keymaps")
require("weihang.autocommands")
require("weihang.lazy")
-- require("weihang.lsp")
--
-- require("weihang.nvim-surround")
-- require("weihang.catppuccin")
-- require("weihang.cmp")
-- require("weihang.telescope")
-- require("weihang.autopairs")
-- require("weihang.comment")
-- require("weihang.treesitter")
-- require("weihang.gitsigns")
-- require("weihang.nvim-tree")
-- require("weihang.lualine")
-- require("weihang.toggleterm")
-- require("weihang.project")
-- require("weihang.impatient")
-- require("weihang.indentline")
-- require("weihang.alpha")
-- require("weihang.bufferline")
-- require("weihang.luasnip")
-- require("weihang.trouble")
-- require("weihang.lsp_signature")
-- require("weihang.lightspeed")
-- require("weihang.auto-session")
-- require("weihang.fugitive")
-- require("weihang.undotree")
-- require("weihang.noice")
